USE retail_analysis;


-- =========================================================
-- 1. CUSTOMER SALES SUMMARY
-- =========================================================
-- Measures orders, units, revenue and gross profit
-- generated by each customer.

SELECT
    c.CustomerKey,
    c.Name,
    c.Gender,
    c.City,
    c.State,
    c.Country,
    c.Continent,

    COUNT(DISTINCT s.Order_Number) AS orders,

    SUM(s.Quantity) AS units_purchased,

    ROUND(
        SUM(
            s.Quantity * p.Unit_Price_USD
        ),
        2
    ) AS revenue,

    ROUND(
        SUM(
            s.Quantity *
            (p.Unit_Price_USD - p.Unit_Cost_USD)
        ),
        2
    ) AS gross_profit

FROM customers AS c

JOIN sales AS s
    ON c.CustomerKey = s.CustomerKey

JOIN products AS p
    ON s.ProductKey = p.ProductKey

GROUP BY
    c.CustomerKey,
    c.Name,
    c.Gender,
    c.City,
    c.State,
    c.Country,
    c.Continent

ORDER BY
    revenue DESC;


-- =========================================================
-- 2. TOP 20 CUSTOMERS BY REVENUE
-- =========================================================

SELECT
    c.CustomerKey,
    c.Name,
    c.Country,

    COUNT(DISTINCT s.Order_Number) AS orders,

    SUM(s.Quantity) AS units_purchased,

    ROUND(
        SUM(
            s.Quantity * p.Unit_Price_USD
        ),
        2
    ) AS revenue

FROM customers AS c

JOIN sales AS s
    ON c.CustomerKey = s.CustomerKey

JOIN products AS p
    ON s.ProductKey = p.ProductKey

GROUP BY
    c.CustomerKey,
    c.Name,
    c.Country

ORDER BY
    revenue DESC

LIMIT 20;


-- =========================================================
-- 3. CUSTOMER ORDER FREQUENCY
-- =========================================================
-- Classifies customers according to how many orders
-- they placed.

WITH customer_orders AS (
    SELECT
        CustomerKey,
        COUNT(DISTINCT Order_Number) AS orders
    FROM sales
    GROUP BY CustomerKey
)

SELECT
    CASE
        WHEN orders = 1 THEN '1 Order'
        WHEN orders BETWEEN 2 AND 4 THEN '2-4 Orders'
        WHEN orders BETWEEN 5 AND 9 THEN '5-9 Orders'
        ELSE '10+ Orders'
    END AS customer_segment,

    COUNT(*) AS customers,

    ROUND(
        AVG(orders),
        2
    ) AS average_orders

FROM customer_orders

GROUP BY
    CASE
        WHEN orders = 1 THEN '1 Order'
        WHEN orders BETWEEN 2 AND 4 THEN '2-4 Orders'
        WHEN orders BETWEEN 5 AND 9 THEN '5-9 Orders'
        ELSE '10+ Orders'
    END

ORDER BY
    customers DESC;


-- =========================================================
-- 4. CUSTOMER REVENUE SEGMENTS
-- =========================================================
-- Groups customers based on total revenue generated.

WITH customer_revenue AS (
    SELECT
        CustomerKey,
        SUM(
            Quantity * p.Unit_Price_USD
        ) AS revenue

    FROM sales AS s

    JOIN products AS p
        ON s.ProductKey = p.ProductKey

    GROUP BY
        CustomerKey
)

SELECT
    CASE
        WHEN revenue < 100 THEN 'Under $100'
        WHEN revenue < 500 THEN '$100-$499'
        WHEN revenue < 1000 THEN '$500-$999'
        WHEN revenue < 5000 THEN '$1,000-$4,999'
        ELSE '$5,000+'
    END AS customer_segment,

    COUNT(*) AS customers,

    ROUND(
        SUM(revenue),
        2
    ) AS total_revenue,

    ROUND(
        AVG(revenue),
        2
    ) AS average_customer_revenue

FROM customer_revenue

GROUP BY
    CASE
        WHEN revenue < 100 THEN 'Under $100'
        WHEN revenue < 500 THEN '$100-$499'
        WHEN revenue < 1000 THEN '$500-$999'
        WHEN revenue < 5000 THEN '$1,000-$4,999'
        ELSE '$5,000+'
    END

ORDER BY
    MIN(revenue);


-- =========================================================
-- 5. AVERAGE CUSTOMER VALUE
-- =========================================================

WITH customer_revenue AS (
    SELECT
        CustomerKey,
        SUM(
            Quantity * p.Unit_Price_USD
        ) AS revenue

    FROM sales AS s

    JOIN products AS p
        ON s.ProductKey = p.ProductKey

    GROUP BY
        CustomerKey
)

SELECT
    COUNT(*) AS purchasing_customers,

    ROUND(
        SUM(revenue),
        2
    ) AS total_customer_revenue,

    ROUND(
        AVG(revenue),
        2
    ) AS average_customer_revenue,

    ROUND(
        MIN(revenue),
        2
    ) AS minimum_customer_revenue,

    ROUND(
        MAX(revenue),
        2
    ) AS maximum_customer_revenue

FROM customer_revenue;


-- =========================================================
-- 6. CUSTOMER REVENUE BY COUNTRY
-- =========================================================

SELECT
    c.Country,

    COUNT(DISTINCT c.CustomerKey) AS customers,

    COUNT(DISTINCT s.Order_Number) AS orders,

    ROUND(
        SUM(
            s.Quantity * p.Unit_Price_USD
        ),
        2
    ) AS revenue,

    ROUND(
        SUM(
            s.Quantity *
            (p.Unit_Price_USD - p.Unit_Cost_USD)
        ),
        2
    ) AS gross_profit

FROM customers AS c

JOIN sales AS s
    ON c.CustomerKey = s.CustomerKey

JOIN products AS p
    ON s.ProductKey = p.ProductKey

GROUP BY
    c.Country

ORDER BY
    revenue DESC;


-- =========================================================
-- 7. CUSTOMER REVENUE BY CONTINENT
-- =========================================================

SELECT
    c.Continent,

    COUNT(DISTINCT c.CustomerKey) AS customers,

    COUNT(DISTINCT s.Order_Number) AS orders,

    ROUND(
        SUM(
            s.Quantity * p.Unit_Price_USD
        ),
        2
    ) AS revenue

FROM customers AS c

JOIN sales AS s
    ON c.CustomerKey = s.CustomerKey

JOIN products AS p
    ON s.ProductKey = p.ProductKey

GROUP BY
    c.Continent

ORDER BY
    revenue DESC;


-- =========================================================
-- 8. REVENUE BY GENDER
-- =========================================================

SELECT
    c.Gender,

    COUNT(DISTINCT c.CustomerKey) AS customers,

    COUNT(DISTINCT s.Order_Number) AS orders,

    SUM(s.Quantity) AS units_purchased,

    ROUND(
        SUM(
            s.Quantity * p.Unit_Price_USD
        ),
        2
    ) AS revenue

FROM customers AS c

JOIN sales AS s
    ON c.CustomerKey = s.CustomerKey

JOIN products AS p
    ON s.ProductKey = p.ProductKey

GROUP BY
    c.Gender

ORDER BY
    revenue DESC;


-- =========================================================
-- 9. CUSTOMER REPEAT PURCHASE RATE
-- =========================================================
-- Measures the percentage of purchasing customers who
-- placed more than one order.

WITH customer_orders AS (
    SELECT
        CustomerKey,
        COUNT(DISTINCT Order_Number) AS orders
    FROM sales
    GROUP BY CustomerKey
)

SELECT
    COUNT(*) AS purchasing_customers,

    SUM(
        CASE
            WHEN orders > 1 THEN 1
            ELSE 0
        END
    ) AS repeat_customers,

    ROUND(
        SUM(
            CASE
                WHEN orders > 1 THEN 1
                ELSE 0
            END
        )
        /
        COUNT(*) * 100,
        2
    ) AS repeat_customer_rate

FROM customer_orders;


-- =========================================================
-- 10. CUSTOMER REVENUE CONCENTRATION
-- =========================================================
-- Measures how much revenue is generated by the top 10%
-- of customers.

WITH customer_revenue AS (
    SELECT
        CustomerKey,

        SUM(
            Quantity * p.Unit_Price_USD
        ) AS revenue

    FROM sales AS s

    JOIN products AS p
        ON s.ProductKey = p.ProductKey

    GROUP BY
        CustomerKey
),

ranked_customers AS (
    SELECT
        CustomerKey,
        revenue,

        NTILE(10) OVER (
            ORDER BY revenue DESC
        ) AS revenue_decile

    FROM customer_revenue
)

SELECT
    ROUND(
        SUM(
            CASE
                WHEN revenue_decile = 1
                THEN revenue
                ELSE 0
            END
        ),
        2
    ) AS top_10_percent_revenue,

    ROUND(
        SUM(revenue),
        2
    ) AS total_revenue,

    ROUND(
        SUM(
            CASE
                WHEN revenue_decile = 1
                THEN revenue
                ELSE 0
            END
        )
        /
        SUM(revenue) * 100,
        2
    ) AS top_10_percent_revenue_share

FROM ranked_customers;


-- =========================================================
-- 11. NEW VS RETURNING CUSTOMERS BY YEAR
-- =========================================================
-- Classifies a customer's first purchase year and compares
-- first-time versus returning activity.

WITH customer_orders AS (
    SELECT
        CustomerKey,
        Order_Number,
        MIN(Order_Date) AS order_date
    FROM sales
    GROUP BY
        CustomerKey,
        Order_Number
),

customer_first_order AS (
    SELECT
        CustomerKey,
        MIN(order_date) AS first_order_date
    FROM customer_orders
    GROUP BY
        CustomerKey
)

SELECT
    YEAR(co.order_date) AS sales_year,

    COUNT(DISTINCT
        CASE
            WHEN YEAR(co.order_date)
                 = YEAR(cfo.first_order_date)
            THEN co.CustomerKey
        END
    ) AS new_customers,

    COUNT(DISTINCT
        CASE
            WHEN YEAR(co.order_date)
                 > YEAR(cfo.first_order_date)
            THEN co.CustomerKey
        END
    ) AS returning_customers

FROM customer_orders AS co

JOIN customer_first_order AS cfo
    ON co.CustomerKey = cfo.CustomerKey

GROUP BY
    YEAR(co.order_date)

ORDER BY
    sales_year;
